services:
  - type: web
    name: textile-api
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        value: "mongodb+srv://kishoreremalli46_db_user:jYTUiDZKPpikEp7k@cluster0.s4w3wkv.mongodb.net/?appName=Cluster0"
      - key: DB_NAME
        value: "textile_traceability"
      - key: CORS_ORIGINS
        value: "https://textile-dynamic.vercel.app,http://localhost:3000"
      - key: JWT_SECRET_KEY
        value: "textile-trace-super-secret-key-2024-production-ready"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "480"
